### ISSUE TITLE
Hovering issue

### ISSUE THREAD

**Issue by aloysiuss** [SaiyajinK/Minimal-Dark-for-Steam#10]
![hovering-issue](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/64868146/7373d18e-2b80-4b97-a35c-4a92ac6adae8)

AFAIK it shouldn't look like this, but its next to the minimize, maximize and close buttons.
Its on the name of your profile, like said, as far as i know it shouldn't be look like this but i could be wrong.

**Comment by SaiyajinK** [comment]
Yes indeed when the address bar is visible the mention "manage my account" is overlapped by the latter. I fixed that, i reduced the padding and it displays correctly now :

![image](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/105972098/012eb4a4-3373-42b6-8f96-761430f17133)

I will update the skin shortly and it will include the fix 👍🏻 

EDIT : [2.9.9](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/releases/tag/2.9.9) is available
