### ISSUE TITLE
Friends List

### ISSUE THREAD

**Issue by madmaxgrey** [SaiyajinK/Minimal-Dark-for-Steam#12]
the friends list needs adjustment for favorited friends
![image](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/50429125/c1f96d3e-3f6a-43f3-8551-ecd20da3a6b4)

**Comment by SaiyajinK** [comment]
yes indeed, I just fixed it, update on your side and it will be good :

![image](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/105972098/683fe50b-f6ee-496a-bb0f-db652c007aa0)

**Comment by madmaxgrey** [comment]
thank you :)
