### ISSUE TITLE
[REQUEST] Some minor modifications

### ISSUE THREAD

**Issue by OsuCelsius** [SaiyajinK/Minimal-Dark-for-Steam#13]
Hello, love your theme, I have some suggerences:
- Can you please make the top left steam button just the icon, without the Steam text? 
- A dedicated button in the top right for opening Steam Chat

**Comment by SaiyajinK** [comment]
regarding the text of the button I was planning to remove it later but following your request I am doing it straight away.

it gives that :
![image](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/105972098/71183e00-3c9f-41ac-a3f1-a5e3db554bea)

regarding the friends button, the contacts are accessible directly from the Steam icon in the taskbar or from the contact button at the top left so I would not put a dedicated button on the right (unless there is a drastic change in the design but even with i don't think so).

the skin will be updated soon and will include the modification.

**Comment by OsuCelsius** [comment]
Thanks for removing the steam text
EDIT: I don't know how it will look but how about instead of making more padding between icons, you include the page backward/forward in that grid?, to avoid things like this when the window is small
![image](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/53451135/ae8200f6-53f4-4a27-921d-cbde7cbe1f23)


I understand why you don't want to make the chat button, I asked for it because I use the Steam Chat to enter asf commands, so I use it quite a lot and you need to make 2 clicks instead of one

**Comment by SaiyajinK** [comment]
Yes i noticed this problem from the first versions. 
I haven't looked into it yet, I will, but not right away. 
On vanilla skin this doesn't happen because the tabs are below the top bar.
I'm closing the issue/request.
