### ISSUE TITLE
VR Icon Seperation not displaying correctly on full screen.

### ISSUE THREAD

**Issue by Mariobruh64** [SaiyajinK/Minimal-Dark-for-Steam#14]
Hey, small update on the VR icon. When full screen, the icon loses its separation from the downloads button and top bar.
![vr_icon](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/171868875/b9261a38-57c1-4334-884e-5576ed6f7fe6)

**Comment by SaiyajinK** [comment]
Yes, I will update to fix this in a few minutes, update or restart Steam for the changes to take effect:

![image](https://github.com/user-attachments/assets/09f98a36-e7ed-4c14-9980-bd750471401f)

![image](https://github.com/user-attachments/assets/533b1e70-b8ff-4b6c-97be-1680762e95a3)


Note: you will notice that the gray bar on the right is displayed correctly in maximized but is 1px thicker in windowed mode, I will try to look for myself if I have some time but in the meantime it will be displayed this way.

**Comment by Mariobruh64** [comment]
Can confirm what you posted, thank you for looking into this nitpicky stuff. The download button seems to be a couple pixels off going down now as well however on my side on both fullscreen and window. Otherwise it's perfect.

![Screenshot 2024-07-15 141319](https://github.com/user-attachments/assets/8b1c788c-8adb-45f8-baf8-3fd33c5af07b)
![Screenshot 2024-07-15 141329](https://github.com/user-attachments/assets/9a1e9ed6-d298-491e-aa45-842dcacac69e)

**Comment by SaiyajinK** [comment]
I am not reproducing the problem. 
Are you on Windows 10 ? the interfaces are slightly different which may cause the problem.

**Comment by Mariobruh64** [comment]
I am on Windows 11.

**Comment by Mariobruh64** [comment]
On Steam bootup it seems to be fine till I access the Library page, then it seems to lose the top bar except the download button.

[steam.webm](https://github.com/user-attachments/assets/905c99fb-745f-4332-9609-8a4bba198f7c)

**Comment by Mariobruh64** [comment]
Okay I got it to be reproducible on my side. If you are fullscreen before accessing the library, then access it, it shifts around. If you access the library while in window mode, then fullscreen. It doesn't cause it and everything stays where it is.

**Comment by SaiyajinK** [comment]
it's very surprising. I made a change, update the skin and tell me if it's good

**Comment by Mariobruh64** [comment]
We are good, everything looks good. Thanks again for looking into it!

**Comment by SaiyajinK** [comment]
All right i close the issue.
