### ISSUE TITLE
No Friends button

### ISSUE THREAD

**Issue by Cheesjry** [SaiyajinK/Minimal-Dark-for-Steam#17]
literally that, there is no button to easily access the friends tab

**Comment by SaiyajinK** [comment]
I deliberately chose to hide it.
But it is accessible from the top bar or the taskbar:

![image](https://github.com/user-attachments/assets/810313ff-98fb-497f-a53d-a8579ce6b5fd)

![image](https://github.com/user-attachments/assets/e701078c-0018-416f-81df-9cd85914f716)

You just have to get used to it. One more click is not "difficult" !
If your question is whether I plan to put the friend button back somewhere ? no, sorry.

**Comment by SaiyajinK** [comment]
I deliberately chose to hide it.
But it is accessible from the top bar or the taskbar:

![image](https://github.com/user-attachments/assets/810313ff-98fb-497f-a53d-a8579ce6b5fd)

![image](https://github.com/user-attachments/assets/e701078c-0018-416f-81df-9cd85914f716)

You just have to get used to it. One more click is not "difficult" !
If your question is whether I plan to put the friend button back somewhere ? no, sorry.
