### ISSUE TITLE
Webkit miss alignment

### ISSUE THREAD

**Issue by madmaxgrey** [SaiyajinK/Minimal-Dark-for-Steam#18]
on a game page for DLC's & soundtracks fully up to date on the skin as of few hours ago
![image](https://github.com/user-attachments/assets/9e6e4633-2b67-4d16-b36e-8fdc84d12a0f)

**Comment by SaiyajinK** [comment]
Fixed, update the skin.

![image](https://github.com/user-attachments/assets/a07e23d0-9c02-4c02-8b4b-5496042e2c21)

**Comment by madmaxgrey** [comment]
thank you :)
