### ISSUE TITLE
Invite to Steam Play Together overlap

### ISSUE THREAD

**Issue by Mariobruh64** [SaiyajinK/Minimal-Dark-for-Steam#19]
The profile picture overlaps the "Invite anyone to play" Steam Play together banner on compatible games.
![image](https://github.com/user-attachments/assets/23d19df1-5f98-4c60-932e-5c0acc9d3fdd)

**Comment by SaiyajinK** [comment]
yes I saw that this morning and I corrected it :

![explorer_mK8eVlpFFt](https://github.com/user-attachments/assets/39ca276c-8a6f-4c86-b4e2-3c054cd3a3c7) ![explorer_larIJAjP4H](https://github.com/user-attachments/assets/83cb51a1-27ec-485c-a058-be4952e88541)

update skin 👍🏻
