### ISSUE TITLE
Avatar and name may overlap each other

### ISSUE THREAD

**Issue by 1012796366** [SaiyajinK/Minimal-Dark-for-Steam#20]
Reproduce the problem by setting "Friends & Chat -> Dock chats to the friends list" to on.
![QQ20240921-131524](https://github.com/user-attachments/assets/5e8780bd-1d85-49ea-95a5-d10d28f504ea)
![QQ20240921-131628](https://github.com/user-attachments/assets/f754aa99-9264-4e46-9014-47b39261ee84)

**Comment by SaiyajinK** [comment]
it's fixed, update the skin 👍🏻 

![image](https://github.com/user-attachments/assets/3e830b2f-a162-46ed-b2fa-df4bfc2f50f2)

**Comment by 1012796366** [comment]
Awesome!
