### ISSUE TITLE
[QUESTION] Changing chat messages color

### ISSUE THREAD

**Issue by CupCake7633** [SaiyajinK/Minimal-Dark-for-Steam#21]
Is there a way to change the color of messages from green and blue back to white?

**Comment by SaiyajinK** [comment]
yes, open the file `friend.custom.css` and edit lines `415` and `419`

with `color: #ffffff !important;` or `color: white !important;`

or any other desired color (blue, red, yellow, green...)
This will need to be done with every update.

**Comment by SaiyajinK** [comment]
yes, open the file `friend.custom.css` and edit lines `415` and `419`

with `color: #ffffff !important;` or `color: white !important;`

or any other desired color (blue, red, yellow, green...)
This will need to be done with every update.

**Comment by CupCake7633** [comment]
It worked, thank you!
