### ISSUE TITLE
[REQUEST] Add back the Restart Option in the menu

### ISSUE THREAD

**Issue by GrPK** [SaiyajinK/Minimal-Dark-for-Steam#22]
Hello! 

I know that some time ago there was an option to restart steam from the left upper-side menu, but since some updates I can't find the option anymore. Is there any way to re-enable it, I found it very useful.

Thanks!

**Comment by SaiyajinK** [comment]
Yes I removed the script from the skin because it was broken in a previous update.
I will add it back if it is updated.

`F5` lets you reload the skin. No similar option to reboot. at least not to my knowledge. Maybe there is a command to enter in the console for reboot, but I don't know it.

**Comment by GrPK** [comment]
I don't know if the script used is this one, found one on GitLab and the author sustains that it still works.

https://gitlab.com/arno-qs/steam-restart

Thanks anyways!

**Comment by SaiyajinK** [comment]
I looked at the gitlab link and the form of the code is the old skin architecture (when steam officially supported themes) before the new UI update..

the code is not something I know well so I won't comment.

I'll look into it when I have a bit more time

**Comment by SaiyajinK** [comment]
I looked but the solution does not seem to work on the latest stable update of Steam, moreover it is an external solution and not integrated into Steam.

If a stable and functional method arrives in the future we will work on it.
