### ISSUE TITLE
Friend List broken in Compact View

### ISSUE THREAD

**Issue by dolixec** [SaiyajinK/Minimal-Dark-for-Steam#24]
![j4kPsbq](https://github.com/user-attachments/assets/654ad828-9b9c-49e4-a516-70f56e5f193e)
As you can see, the avatars are getting out of their bounds in Compact View of Friends List

**Comment by SaiyajinK** [comment]
well, I updated the compact list format, update the skin and it should be good. 👍🏻  

![image](https://github.com/user-attachments/assets/4791cba2-7f4f-49d4-868d-38bba71cd325)
