### ISSUE TITLE
Request : Proper alignment of the chat name and the date

### ISSUE THREAD

**Issue by dolixec** [SaiyajinK/Minimal-Dark-for-Steam#25]
![HZad14v](https://github.com/user-attachments/assets/078ac15f-be05-4e1e-b58b-b934f2e38dab)
As you can see in the image, the date and time are well off the alignment of the name of the person. I think it'd look better if you try to bring them to the same position.

**Comment by SaiyajinK** [comment]
An update must have broken the layout, it wasn't laid out that way before. Anyway I adjusted the code to get a correct visual. 

![image](https://github.com/user-attachments/assets/0b9dc487-0cae-4090-b4cf-792ea9c64384)

Update the skin. 👍🏻
