### ISSUE TITLE
Friend List favorites overlap

### ISSUE THREAD

**Issue by Mariobruh64** [SaiyajinK/Minimal-Dark-for-Steam#26]
Anybody in your friend's favorites bar has their name and game icon covering them.
![Untitled](https://github.com/user-attachments/assets/279266e9-f8e8-477c-af0d-4a10ab2a0408)

**Comment by SaiyajinK** [comment]
Fixed, update the skin 👍🏻 

![image](https://github.com/user-attachments/assets/4763e5cd-e22c-483c-a88d-d871b89108ce)
