### ISSUE TITLE
Friends playing containter goes outside the box.

### ISSUE THREAD

**Issue by Mariobruh64** [SaiyajinK/Minimal-Dark-for-Steam#28]
![steam](https://github.com/user-attachments/assets/87c663ea-4f01-40b7-bc8a-1f3496d97c6d)

**Comment by SaiyajinK** [comment]
I don't have any friends online or in game at the time I'm writing this message, but I made a modification in the siderbar.css file, update on your side and tell me if it's good.

**Comment by SaiyajinK** [comment]
I don't have any friends online or in game at the time I'm writing this message, but I made a modification in `siderbar.css` file, update on your side and tell me if it's good.

**Comment by SaiyajinK** [comment]
I don't have any friends online or in game at the time I'm writing this message, but I made a modification in `siderbar.css`, update on your side and tell me if it's good.

**Comment by Mariobruh64** [comment]
Yep, it's good now! 👍
