### ISSUE TITLE
Add to Cart button in Wishlist size issue

### ISSUE THREAD

**Issue by dolixec** [SaiyajinK/Minimal-Dark-for-Steam#29]
![cyzZBYQ](https://github.com/user-attachments/assets/f0ea9f05-af25-42cb-ad7c-23086acd9027)
It seems the size, or the placement is not centered. Don't know if it's supposed to look like this, I remember it being a bit different

**Comment by SaiyajinK** [comment]
where does this happen ?

**Comment by dolixec** [comment]
Store -> Wishlist
It seems it got fixed by itself? Don't know what happened to be honest, but it's been like that for 2 days, and now suddenly is back to normal.

**Comment by SaiyajinK** [comment]
Sometimes yes, on Steam they have to make some changes that cause these anomalies... but it always comes back to normal with a little wait. In any case on my side I haven't touched anything, but so much the better if it works again. I'm closing the request.
