### ISSUE TITLE
Unread message in friend list gets bugged

### ISSUE THREAD

**Issue by dolixec** [SaiyajinK/Minimal-Dark-for-Steam#34]
![yu3gWq8](https://github.com/user-attachments/assets/6720389f-fe41-4cc9-869a-ea74ac6f475f)
When you receive a new message and you go in the friend list to read it, the friend list gets bugged and you can open the chat only if you click in that small box on the left

**Comment by SaiyajinK** [comment]
@dolixec update the skin it should be good. 👍🏻

**Comment by dolixec** [comment]
Thank you for the fast fix! Marking it as closed
