### ISSUE TITLE
[Bug] Incorrect display of game compatibility with Steam Deck

### ISSUE THREAD

**Issue by OwlVoid** [SaiyajinK/Minimal-Dark-for-Steam#35]
In the Library section, when you hover over the game, the Steam Deck compatibility icon does not display correctly (in the original it is located right in the corner, but here it is almost in the middle).
![image](https://github.com/user-attachments/assets/7243229b-b2ec-4747-b875-ded5488ae0c9)

**Comment by SaiyajinK** [comment]
@OwlVoid I don't see this in my library (I don't have a steam deck maybe that's the cause)

Where exactly is it located? (take a full screenshot of steam) maybe that will give me an indication.

**Comment by OwlVoid** [comment]
Steam -> Settings -> Library -> "Show information about Steam Deck compatibility in the library"

**Comment by SaiyajinK** [comment]
ok, I fixed the appearance of the button it should be better :

![steamwebhelper_mGHZyeV4fP](https://github.com/user-attachments/assets/c6be50ec-e0d6-4988-b472-311d763c9ea0)

update skin and tell me.

**Comment by OwlVoid** [comment]
Yes, everything works, but only if you use an average interface size. Yes, I know that you recommend using a named one, but it's more convenient for me to sit on the automatic one. So yes, the problem is solved.

**Comment by SaiyajinK** [comment]
yes i understand. i made some changes to have the best possible layout with the large and medium interface. Update the skin again on your side.

**Comment by OwlVoid** [comment]
Is that how it should be?
![image](https://github.com/user-attachments/assets/460939a6-b943-4203-8716-c8c7dde60865)

**Comment by SaiyajinK** [comment]
from your answer I guess it doesn't work, so I decided to hide the 'download' button on uninstalled games (still accessible by right-clicking > install).

![steamwebhelper_UvccIeAqdC](https://github.com/user-attachments/assets/fccf3247-91e8-4c5a-9027-5beb33a3d572)

Update skin,

**Comment by OwlVoid** [comment]
What should I do if the family library is connected and you have two copies of the game for the family?
![image](https://github.com/user-attachments/assets/3de3b3d8-9665-4317-9e1b-606976f8f42b)
![image](https://github.com/user-attachments/assets/da1dbe47-d5e3-4081-81d5-ad7afc01c63d)

**Comment by SaiyajinK** [comment]
I adapted this for the flyover

![vmware_b4nEFbCI5h](https://github.com/user-attachments/assets/0c76710e-1f0c-4eb6-befd-d7d136f666f0)

I also took the opportunity to match the family part to the skin.
Update skin.
