### ISSUE TITLE
A question or an improvement.

### ISSUE THREAD

**Issue by OwlVoid** [SaiyajinK/Minimal-Dark-for-Steam#36]
Is there any way to increase the area that can be clicked on when closing or minimizing the window?

I can't close or hide the window the first time.
For clarity, I'll attach how it's done in stock.
![image](https://github.com/user-attachments/assets/24460340-9500-4639-aff7-bedadd4b0721)

**Comment by SaiyajinK** [comment]
I had planned to do this later in my roadmap but I'm going to move it forward to improve your experience.

This is just a concept but here's what it should look like :

![Photos_Evi2c2BTU6](https://github.com/user-attachments/assets/f61c2835-8fd0-425f-8606-ac410c06c77c)

I was using svgs with webkit-masks but I have to rewrite everything to do this so I don't know when I'll make it available.

**Comment by SaiyajinK** [comment]
Update skin 👍🏻  some changes come later but the basis is there.
