### ISSUE TITLE
A malfunction in the skin or in the steam.

### ISSUE THREAD

**Issue by OwlVoid** [SaiyajinK/Minimal-Dark-for-Steam#37]
I just noticed that there is such an overlap in the "Recent games" section in the library. I don't know if this is a bug or not, but I decided to let you know.
![image](https://github.com/user-attachments/assets/880e5b84-6743-49c2-abec-e6d2e4d103d7)

**Comment by OwlVoid** [comment]
Still, the problem is not Steam.
![image](https://github.com/user-attachments/assets/013c83ff-38d1-4b9d-a8dd-cba19fb13e2a)

**Comment by SaiyajinK** [comment]
update skin.

![image](https://github.com/user-attachments/assets/09ab81c8-a076-4526-a8fb-3ec1d753cba5)
