### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by OwlVoid** [SaiyajinK/Minimal-Dark-for-Steam#38]
The list of friends currently playing the game is not displayed the way it is on your page, is that how it should be?
![image](https://github.com/user-attachments/assets/c44f0f59-e701-47e6-9a35-14d9b9e60de0)
![image](https://github.com/user-attachments/assets/6ea328b7-5e9e-496e-9354-750baef995ac)

**Comment by SaiyajinK** [comment]
yes it's normal, the friends list takes this display when several of your contacts play the same game (or together).
Look at mine currently it's not the same as the screenshot either

![image](https://github.com/user-attachments/assets/23fe9643-6de0-459e-a7dc-307ec1622a41)
