### ISSUE TITLE
Demande d'amélioration visuelle

### ISSUE THREAD

**Issue by gsrd90** [SaiyajinK/Minimal-Dark-for-Steam#4]
@SaiyajinK bonjour, déjà merci pour ce thème incroyable !!! 
je ne suis pas bilingue je parle le franglais et comme j'ai vu que tu étais de france je mets ma demande en français. je ne sais pas si je dois déposer ça ici mais est-il possible de faire une demande d'amélioration visuelle sur une partie du skin non retravaillée ?

 merci d'avance pour la réponse.

**Comment by SaiyajinK** [comment]
salut, ouai bien sur pas de problème. 👍🏻 
Il faut juste me dire de quelle partie tu me parles en fait parce que j'ai aucune information 😅

**Comment by gsrd90** [comment]
Ce serait pour faire l'inventaire stp.
et j'ai eu une mise à jour de Steam, le thème ne marche plus...

**Comment by ShadowyBerry** [comment]
Steam a fait une mise à jour sur la branche publique. Ce qui a cassé SFP, Millenium et la plupart des skins.

**Comment by SaiyajinK** [comment]
> Steam a fait une mise à jour sur la branche publique. Ce qui a cassé SFP, Millenium et la plupart des skins.

Yes, en l'état actuel le thème est cassé. Mais j'ai déjà utilisé le mapper de ShadowM et il est déjà opérationnel sur la nouvelle interface (Millennium à été également mis à jour pour réapparaitre dans les paramètres) :

![a588YfAO9p](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/105972098/fea9be09-af44-4f05-bef6-b3060d4c0fa6)

Pour SFP il faudra regarder si le soft est mis à jour pour supporter la nouvelle monture.

> Ce serait pour faire l'inventaire stp. et j'ai eu une mise à jour de Steam, le thème ne marche plus...

Ça marche, je finalise là et je balance la mise à jour 👍🏻

**Comment by SaiyajinK** [comment]
@gsrd90 c'est bon c'est mis à jour pour le thème tout devrait être revenu à la normale.

En ce qui concerne l'inventaire, je ferai l'historique des échanges, cadeaux etc plus dans les prochains jours, mais la page principale est faite 👍🏻

**Comment by gsrd90** [comment]
ça marche merci pour la rapidité !!!! =) =) =) 
et oui le thème refonctionne !!
