### ISSUE TITLE
Theme tweaking assistance

### ISSUE THREAD

**Issue by DrR0Ck** [SaiyajinK/Minimal-Dark-for-Steam#5]
Hi there!  I love your theme, but would like to make a small number of minor tweaks.  Unfortunately, my grasp of the code and where to look to make the tweaks is not strong enough to figure this out for myself.  I am hoping you can point me in the right direction, but if this request is inappropriate as a Github issue, please feel free to close the question.

I'd like to make the following changes to the theme:

- Increase the font size, change case to upper, and perhaps bold for the topmost navigation (Store, Library, Community, etc.)
- Increase the font size, change text and highlight colors for the library left-hand game listing
- Increase the sizes of the game thumbnails in recent games and below library categories; I currently have the size set to "Medium" but "Large" is way larger than I would prefer.

Thanks!

**Comment by SaiyajinK** [comment]
Hi, this is not a problem with Minimal, it's simply that Steam does not include any option to adjust the font size in the settings. We can define it manually by modifying each block in the code but it is a lot of work. You can change the Windows dpi but the problem is that it will not only apply to Steam but to the entire system. The only viable solution for me is to force an upscale of the Steam interface from the shortcut by adding the argument `-forcedesktopscaling 1.25` (the value can be increased or decreased depending on your needs) and then adjusts the size of the thumbnails from the settings.

![uhB7hFE4Mn](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/105972098/0d6c20d7-56e8-4f6c-b755-3c15e96bd695)

regarding the top bar, you can modify `libraryroot.custom.css` and edit lines `687`, `689`, `699` and `701`

`font-weight: bold !important;`
`text-transform: uppercase !important;`

This will have to be done again during each update.

**Comment by DrR0Ck** [comment]
Thank you VERY much for your input!  I try to be self sufficient but so many of the labels are very cryptic now: ".RtSv39ZoBOySnb8XQ5hJf._3L1c8C0o_xXzPy26aoLBFd"  I'll give your recommendations a try.  

For the left-hand game list in the library screen, can we adjust font size, color, highlighting?  

Thanks again

**Comment by SaiyajinK** [comment]
yes the beta branch was moved to the stable channel and the latter modified all of the class names, no one really understands why in fact.

To increase the font in the sidebar, open `sidebar.css` and modify line `276`

```
._2-O4ZG0KrnSrzISHBKctFQ ._1vO6BoiVslZgs1kqDGdUs8 {
    padding: 2px 0px 2px 24px !important;
    font-size: 15px !important;
}
```

or another value in font-size déclaration

for the selected color, modify line `143` (for installed games)

```
._2-O4ZG0KrnSrzISHBKctFQ._1UBpAXP408Ez_L_mXhW5Q9._2ws8DONH9fxQjPXEmRpujE {
    color: *your color or your code color* !important;
    margin-left: 2px !important;
}
```

and edit line `154` (for uninstalled games)

```
._2-O4ZG0KrnSrzISHBKctFQ._1UBpAXP408Ez_L_mXhW5Q9._5YTBr7WwIfzVU_3nUtAph {
    color: *your color or your code color* !important;
}
```

**Comment by DrR0Ck** [comment]
Thank you again!  The changes are looking good so far!  

The -forcedesktopscaling option on the shortcut does not appear to be working - at least not for me.  I will keep fiddling with it, but thus far, it hasn't resulted in any kind of change for me.  I have tried values of 1.25, 1.5 and 2.
![image](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/47359983/a7fa53c9-3815-4c64-bcf4-b74f77ede744)

**Comment by SaiyajinK** [comment]
It's weird, it works well for me. 

vanilla : 
![steamwebhelper_9pwzLxwm2V](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/105972098/3c311424-0e0d-40ab-a495-a3a8636fad91)

with argument : 
![steamwebhelper_EuSKqKakDA](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/105972098/2c0f88c1-d87c-4b24-bb8c-bdfaf085bd5c)

I don't know if being on w10 is the cause ? I'm on w11.

once the argument is written, you must apply and restart Steam from the modified shortcut for the changes to take effect (this may be what you have already done but I'm telling you anyway just in case).

You will also need to modify the argument if Steam starts with Windows (with a startup manager for example)

**Comment by DrR0Ck** [comment]
Hmm.   I'll have to keep fiddling with it.  I wouldn't think Win 10 vs 11 should make a difference, but don't know for sure.  And yes, I am making the change to the shortcut when Steam is shut down and starting Steam up after making the change.  In any event, not a deal-breaker.  I appreciate the assistance you have provided; you can close the issue if you like - unless you would like me to post an updated screenshot once I'm done tweaking.  Thanks again for your patience and support!

**Comment by DrR0Ck** [comment]
I got the scaling working:  I had the setting "Scale text and icons to match monitor settings" turned off.  Once I turned that on, the scaling worked!

**Comment by DrR0Ck** [comment]
Very pleased with the result of my edits.  In addition to increasing and bolding the top menu navigation, I have increased the font on the "Steam" button, and added hover behavior and bolding to the selected library item for both installed and uninstalled items.  I'll probably keep tinkering, but in a good place at the moment.  Thanks again for all of your assistance.
![image](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/47359983/befce304-b1d5-4165-b416-1db3f5bfd323)
