### ISSUE TITLE
VR Headset Icon issue

### ISSUE THREAD

**Issue by Mariobruh64** [SaiyajinK/Minimal-Dark-for-Steam#7]
If you have a VR headset, the top bar gets a VR icon and with the theme, it gets put slightly behind the downloads button and doesn't have a border like the rest of the buttons do.
![Screenshot 2024-06-05 163755](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/171868875/2f51d247-9975-4118-9d09-dcda381a5b9b)

**Comment by SaiyajinK** [comment]
I don't have a VR headset anymore, so it's going to be complicated for me to fix this. 
I will look this on my side (without certainties).

**Comment by SaiyajinK** [comment]
@Mariobruh64 I found a way to emulate a VR headset with my Android phone connected to my PC, so I see the icon that is causing the problem :

![image](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/105972098/19a85958-a02a-43d9-8c7a-678860ab34d8)

I will try to make an arrangement with what I have on my side and then I will update and you will give me feedback here.

**Comment by SaiyajinK** [comment]
Here's what it looks like on my side :

![steamwebhelper_NGN6f9ScAE](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/105972098/289e67a2-6545-4c51-897d-023c106f2321)

I will update the skin, test it on your side and let me know if it suits you.

`Edit`: It's updated, i'm waiting for your return to close the issue.

**Comment by Mariobruh64** [comment]
Can confirmed fixed, thank you.

![Screenshot 2024-06-13 123940](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/171868875/b19ff348-0f57-4116-b950-0c6ad62a2ae1)
