### ISSUE TITLE
Idea/suggestion - Layout button

### ISSUE THREAD

**Issue by AuditoQc** [SaiyajinK/Minimal-Dark-for-Steam#8]
First thanks for the skin i really like it !

It's hard to explain, so i used paint to move button and attached the picture result with this message ! I don't know if is possible to move them like that but for me it's more intuitive. I know it's only my opinion and if you don't like it, it's fine :)

- 2 layout idea in the picture [Left & Right] I prefer number 2.
![Minimal Dark - Layout suggestion](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/29949284/2a4d59d5-a4e1-4ef1-9062-2334b064ac08)

**Comment by SaiyajinK** [comment]
@AuditoQc no, I don't plan to change the topbar in short, medium, or long term sorry.

on the other hand if you want this interface, I can give you the code to apply/modify but you will have to redo it after each update:

Go to : `C:\Program Files (x86)\Steam\steamui\skins\Minimal-Dark-for-Steam-root\`

Open `libraryroot.custom.css`

Replace the following lines with the corresponding code using Notepad++:

line `689`:

```
._7AlhCx3XGzBeIrQaCneUD {
 font-size: 13px !important;
 font-weight: 300;
 height: inherit;
 text-transform: none;
 overflow-x: visible;
 cursor: pointer;
 margin-top: 0px;
 border: 1px solid var(--minimal_dark_be_grey);
 border-top: none !important;
 border-bottom: none !important;
 transform: translate(7px, 0px);
}
```

line `763`:

```
._3Z3ohQ8-1NKnCZkbS6fvy {
 display:flex;
 flex-direction: row;
 height: 32px;
 min-height: 32px;
 -webkit-app-region: drag;
 max-width: 500px;
 position: static;
 margin-left: -2px;
 margin-top: 4px;
 border-top: 1px solid var(--minimal_dark_be_grey) !important;
}
```

once the code is applied and saved restart Steam or press F5 and it will give this : 

![image](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/105972098/1335b0d8-9acc-41d9-87bd-bfb013ac19b1)


for layout number 2, the Steam button is affiliated with the menu block (the support menu, display etc.). So unless I modify everything in depth (not complicated but which take time) I won't venture there sorry.

**Comment by AuditoQc** [comment]
Ah, tu parle français ! Merci pour le petit tuto j'vais faire comme ça tantôt :) Justement tantôt je fouillais dans les .css car je voulais changer la couleur de la bar du scrollbar et aussi l'élargir un peu. Ta déjà la VAR pour le rouge de ce que j'ai vue dans config.css et webkit.css [--minimal_dark_red1] code de couleur [#ff0000] Mais j'étais certain ou l'appliquer dans scrollbar.css. petit précision c'est la couleur NO HOVER MOUSE que je voudrais changer

**Comment by SaiyajinK** [comment]
Tu entends quoi par no hover mouse ? quand tu survoles pas avec le pointer de la souris ?

Si c'est ça oui c'est bien dans `scrollbar.css` ligne `3` baisse la valeur de la bordure (border) plus tu descends le nombre plus la barre de défilement sera grosse. 

Et si tu veux changer la couleur quand t'as pas la souris dessus c'est la ligne `2` tu remplaces `var(--minimal_dark_be_grey)` par la couleur ou la variable que tu veux.

**Comment by AuditoQc** [comment]
Salut, merci pour l'aide j'apprécie :)

Oui par "NO HOVER MOUSE" je veux dire quand la souris n'est pas sur la scroll bar.

Cependant, pour la larger ça fonctionner (Pratique pour du 2k) mais pas pour le couleur. Je te join un screenshot.

![Sans titre](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/29949284/04d5f383-d24c-4344-bc1b-2a6655226d21)

**Comment by SaiyajinK** [comment]
désolé je ne sais pas pourquoi je pensais que tu parlais seulement de la barre latérale gauche (la sidebar)... :man_shrugging:

modifie également : 

le fichier `webkit.css` et modifie la valeur de la ligne `113`

```
::-webkit-scrollbar-thumb {
    background-color: var(--minimal_dark_red1) !important;
}
```
et le fichier `friends.custom.css` et modifie la valeur de la ligne `148`

```
.friendsui-container ::-webkit-scrollbar-thumb {
    background-color: var(--minimal_dark_red1) !important;
    border: 4px solid transparent !important;
    border-radius: 20px !important;
}
```

Ça appliquera le rouge sur toutes les scrollbars du skin (la barre latérale, la librairie, le webkit et la liste d'amis).

**Comment by AuditoQc** [comment]
Ça fonctionne ! Super et merci encore.

Merci d'avoir pris du temps surtout. Je suis bien placer pour savoir qu'on à pas toujours envie ou le temps de satisfaire toutes les préférence individuel de chaques personnes.. (Je gère des games servers) Donc j'apprécie énormément.

![Sans titre](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/29949284/04cc647b-ba70-4fc5-b32f-059652f9565c)

**Comment by SaiyajinK** [comment]
Pas de soucis, tant que ça reste raisonnable c'est faisable. 
Mais tout en gardant à l'esprit que toutes les modifications seront effacées lors de chaque mise à jour et tu devras refaire toutes les modifications.

**Comment by SaiyajinK** [comment]
Pas de soucis, tant que ça reste raisonnable c'est faisable.
Mais tout en gardant à l'esprit que toutes les modifications seront effacées lors de chaque mise à jour et tu devras refaire toutes les modifications.
